version: '3.8'

services:
  fastapi-simple-app-no-1:
    build:
      context: .
      dockerfile: fastapi_simple_app/Dockerfile
    command: uvicorn fastapi_simple_app.main:app --host 0.0.0.0 --port 8000
    ports:
      - "1000:8000"
    volumes:
      - .:/app
    restart: always

  fastapi-simple-app-no-2:
    build:
      context: .
      dockerfile: fastapi_simple_app_2/Dockerfile
    command: uvicorn fastapi_simple_app_2.main:app --host 0.0.0.0 --port 8000
    ports:
      - "2000:8000"
    volumes:
      - .:/app
    restart: always